name: Release

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}

    - name: Identify
      run: |
        git config user.name OpenActive Bot
        git config user.email hello@openactive.io

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run tests
      run: bundle exec rspec

    - name: Release based on version.rb
      run: bundle exec rake release
